version: '{build}'
os: Windows Server 2012

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: "-t7z -m0=lzma -mx=9"

  matrix:
    - CI_TEST: ci-fast-212
    - CI_TEST: ci-sbt013

install:
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
  - ps: scoop bucket add versions
  - ps: scoop install sbt0.13

build_script:
  - sbt compile
  
test_script:
  - sbt "%CI_TEST%-windows"

cache:
  - '%USERPROFILE%\.ivy2\cache'
  - '%USERPROFILE%\.sbt'
  - '%LOCALAPPDATA%\Coursier\cache'
  - '%USERPROFILE%\scoop\cache'